# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12c8f6a826a902ec0b41c158d46e22ebe096966bbe4c5ad97255f28d3e2cbc1029d561acc5fba5a001580eb121c2406d9966fce35e0b04537570929995196ffb

test:
  secret_key_base: 5d378b4fcfbd55b2bbbcaf58d9e2a0d3359ab43272f43fc3cd6a11e6d1c7a1d3a362200686ad807ed7d6c0e3d9c0881c4823d9f1d87d4042f26cd1f765459b88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
